version: 0.2
phases:
  install:
    runtime-version:
      docker: 18
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - export TAG=$(date "+%m%d%y%H%M")
      - export REPOSITORY_URI=209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app
    finally:
      - echo Pre Build phase done
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - docker build -t codebuild-rails-app:$TAG .
    finally:
      - echo Build phase done

  post_build:
    commands:
      - docker tag codebuild-rails-app:$TAG 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$TAG
      - docker tag codebuild-rails-app:$TAG 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:latest
      - docker push 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:latest
      - docker push 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$TAG
      - echo Writing image definitions file...
      - printf '[{"name":"batman-villains","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
    finally:
      - echo Post Build phase done

