version: 0.2
env:
  parameter-store:
    SECRETS: "bowens3-ruby-demo"
phases:
  install:
    runtime-version:
      docker: 18
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - export COMMIT_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - export GIT_TAG=$(git tag -l --points-at HEAD)
      - export GIT_BRANCH=$(git branch --show-current)
      - export REPOSITORY_URI=209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app
    finally:
      - echo Pre Build phase done
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - docker build --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t codebuild-rails-app:$COMMIT_TAG .
      - docker run --rm -e CODEBUILD=$SECRETS codebuild-rails-app:$COMMIT_TAG bundle exec rspec
      - docker tag codebuild-rails-app:$COMMIT_TAG 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$COMMIT_TAG
      - docker push 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$COMMIT_TAG
      - docker tag codebuild-rails-app:$COMMIT_TAG 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$GIT_BRANCH
      - docker push 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$GIT_BRANCH
      - if [ -n $GIT_TAG ]; then docker tag codebuild-rails-app:$COMMIT_TAG 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$GIT_TAG; docker push 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$GIT_TAG; fi
      - echo Writing image definitions file...
      - printf '[{"name":"batman-villains","imageUri":"%s"}]' $REPOSITORY_URI:$COMMIT_TAG > imagedefinitions.json
    finally:
      - echo Build phase done
      
artifacts:
    files: imagedefinitions.json
