version: 0.2
env:
  parameter-store:
    SECRETS: "bowens3-ruby-demo"
    SECRET_KEY: "bowens3-key-base"
phases:
  install:
    runtime-version:
      docker: 18
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - GIT_TAG=$(git tag -l --points-at $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - BRANCH=$(echo $CODEBUILD_WEBHOOK_TRIGGER |cut -d"/" -f2)
      - REPOSITORY_URI=209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app
      - export GIT_TAG
      - export BRANCH 
      - export $REPOSITORY_URI
    finally:
      - echo Pre Build phase done
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - docker build --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI --build-arg RAILS_MASTER_KEY=$SECRET_KEY -t codebuild-rails-app:$BRANCH .
      - if [ $BRANCH == "dev" ]; then docker run --rm -e CODEBUILD=$SECRETS codebuild-rails-app:$BRANCH bundle exec rspec; fi
      - docker tag codebuild-rails-app:$BRANCH 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$BRANCH
      - docker push 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$BRANCH
      - if [ ! -z ${GIT_TAG-x} ]; then docker tag codebuild-rails-app:$BRANCH 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$GIT_TAG; docker push 209773529123.dkr.ecr.us-east-1.amazonaws.com/codebuild-rails-app:$GIT_TAG; fi
      - echo Writing image definitions file...
      - printf '[{"name":"batman-villains","imageUri":"%s"}]' $REPOSITORY_URI:$BRANCH > imagedefinitions.json
    finally:
      - echo Build phase done
      
artifacts:
    files: imagedefinitions.json
