version: 0.2
phases:
  install:
    runtime-version:
      ruby: 2.5
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  pre-build:
    commands:
      - gem install bundler
  build:
    commands:
      - bundle install
      - bundle exec rake db:create db:migrate db:seed && bundle exec rake db:migrate RAILS_ENV=test
      - bundle exec rspec